"""Create Search Vector

Revision ID: 0537cdf07c6d
Revises: 1f0663a24fe1
Create Date: 2025-11-09 19:41:35.907399

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0537cdf07c6d"
down_revision: str | Sequence[str] | None = "1f0663a24fe1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            || \n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_products_tsv_gin", "products", ["tsv"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_tsv_gin", table_name="products", postgresql_using="gin")
    op.drop_column("products", "tsv")
    # ### end Alembic commands ###
